@baseUrl = http://localhost:8080/api
@json = application/json

### 게시판 생성
POST {{baseUrl}}/board
Content-Type: {{json}}

{
  "board_name": "board1"
}

### 게시물 등록
POST http://localhost:8080/api/post
Content-Type: application/json

{
  "board_id": 1,
  "username": "tester",
  "password": "pass1",
  "email": "a@a.com",
  "title": "post 1",
  "content": "11111"
}

### 게시물 조회
POST http://localhost:8080/api/post/1
Content-Type: application/json

{
  "password": "pass1"
}

### 게시물 등록
POST http://localhost:8080/api/post
Content-Type: application/json

{
  "board_id": 1,
  "username": "tester2",
  "password": "pass1",
  "email": "b@b.com",
  "title": "post 2",
  "content": "22222"
}

### 게시물 목록 조회
GET http://localhost:8080/api/post/all

### 게시물 삭제
POST http://localhost:8080/api/post/1/delete
Content-Type: {{json}}

{
  "password": "pass1"
}

### 게시물 등록
POST http://localhost:8080/api/post
Content-Type: application/json

{
  "board_id": 1,
  "username": "tester3",
  "password": "pass1",
  "email": "c@c.com",
  "title": "post 3",
  "content": "33333"
}

### 답변 등록
POST http://localhost:8080/api/reply
Content-Type: application/json

{
  "post_id": 3,
  "username": "admin1",
  "title": "answer 1",
  "content": "333 333"
}

### 답변 등록
POST http://localhost:8080/api/reply
Content-Type: application/json

{
  "post_id": 3,
  "username": "admin1",
  "title": "answer 2",
  "content": "333 333 333"
}

### 게시물 조회
POST http://localhost:8080/api/post/3
Content-Type: application/json

{
  "password": "pass1"
}

### 답변 등록 실패
POST http://localhost:8080/api/reply
Content-Type: application/json

{
  "post_id": 100,
  "username": "admin1",
  "title": "answer 2",
  "content": "333 333 333"
}

### 답변 등록
POST http://localhost:8080/api/reply
Content-Type: application/json

{
  "post_id": 3,
  "username": "admin1",
  "title": "answer 3",
  "content": "aaa aaa"
}