services:
  db:
    image: mysql:8.4.3
    container_name: fc-course03-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      MYSQL_DATABASE: simple_board
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: ${LOCAL_DEVDB_PASSWORD}
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --default-time-zone=Asia/Seoul
    volumes:
      - fc-course03-data:/var/lib/mysql
    restart: always
volumes:
  fc-course03-data: